### ISSUE TITLE
<BatteryCharging/> : Wrong Duplicated Icon

### ISSUE THREAD

**Issue by iMahdi1383** [zero-icons/react-huge-icons#13]
In Outline icon mode in "http://zero-icons.ir", the icon for "Battery charging" is wrong. This icon is the same as the "Battery" icon.
![image](https://user-images.githubusercontent.com/35895354/230160256-68c8b58e-5a22-48a9-a043-f47aa649142c.png) ![image](https://user-images.githubusercontent.com/35895354/230160307-aed5f19b-f67d-4203-a63c-6c02c5966f75.png)

**Comment by peymanath** [comment]
Fixed in version 1.2.0
https://www.npmjs.com/package/react-huge-icons
