### ISSUE TITLE
<Battery Horizontal Charging/>: The color of the lightning symbol does not change

### ISSUE THREAD

**Issue by iMahdi1383** [zero-icons/react-huge-icons#14]
In the icon list section at "http://zero-icons.ir", in outline icon mode, various icons can be changed in color. But the color of the lightning symbol in the center of the "BatteryHorizontalCharging" icon does not change.
![image](https://user-images.githubusercontent.com/35895354/230160753-2d77df33-b63c-4ad5-8ea1-61bfc3839800.png) ![image](https://user-images.githubusercontent.com/35895354/230161905-fef025d2-1a82-4757-ae26-8ee08dc6c19f.png) ![image](https://user-images.githubusercontent.com/35895354/230162060-16f98f74-9f11-47ba-ac29-05fc128473c4.png)

**Comment by peymanath** [comment]
Fixed in version 1.2.0
https://www.npmjs.com/package/react-huge-icons
